name: Periodic

on:
  workflow_dispatch:
  schedule:
  - cron: 0 0 * * SUN

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable, beta, nightly]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tests
      run: cargo test
