name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - { name: ubuntu,             os: ubuntu-latest,  cross-target: x86_64-unknown-linux-musl }
          - { name: macos,              os: macos-latest,   cross-target: 'aarch64-apple-darwin' }
          - { name: windows,            os: windows-latest, cross-target: '' }

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: awalsh128/cache-apt-pkgs-action@latest
      if: matrix.os == 'ubuntu-latest'
      with:
        packages: musl-tools
        version: 1.0
    
    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        default: true
        # The macOS AArch64 build is done from an x86_64 macOS CI runner, so
        # it needs to be cross compiled
        target: ${{ matrix.cross-target }}

    - name: Build for linux
      if: matrix.name == 'ubuntu'
      run: make release_lnx
    - name: Build for macOS
      if: matrix.name == 'macos'
      run: make release_mac
    - name: Build for Windows
      if: matrix.name == 'windows'
      run: make release_win
    - uses: actions/upload-artifact@v3
      with:
        path: '*.zip'
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: '[Changelog](https://github.com/dalance/svls/blob/master/CHANGELOG.md)'
        files: '*.zip'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
